import type { INodeProperties } from 'n8n-workflow';

const showFor = { resource: ['videoCaption'] };

export const videoCaptionDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showFor },
		options: [
			{
				name: 'Add Stylish Captions',
				value: 'addStylishCaption',
				action: 'Add stylish captions to a video',
				description: 'Transcribe the audio and burn in animated, word-level captions',
			},
		],
		default: 'addStylishCaption',
	},
	{
		displayName: 'Video Source',
		name: 'inputKey',
		type: 'string',
		required: true,
		displayOptions: { show: showFor },
		default: '',
		placeholder: 'uploads/reel.mp4 or https://example.com/video.mp4',
		description: 'Paste a storage key from your upload step, or a public HTTPS URL',
	},
	{
		displayName: 'How to Get the Result',
		name: 'outputType',
		type: 'options',
		displayOptions: { show: showFor },
		options: [
			{ name: 'File', value: 'file', description: 'Download the file directly when the job completes' },
			{ name: 'Public URL', value: 'public_url', description: 'Get a permanent public link — no authentication needed' },
			{ name: 'Download Link', value: 'signed_url', description: 'Get a temporary download link that expires' },
			{ name: 'Save to Storage Only', value: 'stored', description: 'Store the output in your VideoApiHub storage' },
		],
		default: 'signed_url',
		description: 'How you want to receive the finished captioned video',
	},
	{
		displayName: 'Link Expires After (Seconds)',
		name: 'outputExpiry',
		type: 'number',
		displayOptions: { show: { ...showFor, outputType: ['signed_url'] } },
		typeOptions: { minValue: 60, maxValue: 86400 },
		default: 3600,
		description: 'How long the download link stays active. Default: 1 hour (3600 seconds).',
	},
	{
		displayName: 'Style Preset',
		name: 'stylePreset',
		type: 'options',
		displayOptions: { show: showFor },
		options: [
			{ name: 'Bold Yellow Karaoke', value: 'bold-yellow-karaoke' },
			{ name: 'Cinematic Serif', value: 'cinematic-serif' },
			{ name: 'Clean Minimal', value: 'clean-minimal' },
			{ name: 'Dynamic Size', value: 'dynamic-size' },
			{ name: 'Gradient Glow', value: 'gradient-glow' },
			{ name: 'Kinetic Typography', value: 'kinetic-typography' },
			{ name: 'Meme Impact', value: 'meme-impact' },
			{ name: 'Neon Pop', value: 'neon-pop' },
			{ name: 'Podcast Lower Third', value: 'podcast-lower-third' },
			{ name: 'TikTok White Stroke', value: 'tiktok-white-stroke' },
		],
		default: 'neon-pop',
		description: 'Choose the visual style for your animated captions',
	},
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		typeOptions: { rows: 3 },
		displayOptions: { show: showFor },
		default: '',
		placeholder: 'Emphasize numbers and calls to action',
		description: 'Optional natural-language guidance for the AI style and emphasis plan',
	},
	{
		displayName: 'Add B-Roll Clips',
		name: 'brolls',
		type: 'boolean',
		displayOptions: { show: showFor },
		default: false,
		description: 'Whether to auto-insert relevant b-roll clips around the captions',
	},
	{
		displayName: 'B-Roll Image URLs',
		name: 'brollImages',
		type: 'string',
		typeOptions: { rows: 3 },
		displayOptions: { show: { ...showFor, brolls: [true] } },
		default: '',
		placeholder: 'https://example.com/clip1.jpg, https://example.com/clip2.jpg',
		description: 'Optional comma-separated HTTPS image URLs to use as b-roll sources',
	},
	{
		displayName: 'B-Roll Position',
		name: 'brollPosition',
		type: 'options',
		displayOptions: { show: showFor },
		options: [
			{ name: 'Top', value: 'top' },
			{ name: 'Center', value: 'center' },
			{ name: 'Bottom', value: 'bottom' },
		],
		default: 'top',
		description: 'Where b-roll cutaways are vertically positioned',
	},
	{
		displayName: 'Language Hint',
		name: 'language',
		type: 'string',
		displayOptions: { show: showFor },
		default: '',
		placeholder: 'en',
		description: 'Optional ISO language hint for transcription',
	},
	{
		displayName: 'Output Width (Pixels)',
		name: 'width',
		type: 'number',
		displayOptions: { show: showFor },
		typeOptions: { minValue: 1 },
		default: 1080,
	},
	{
		displayName: 'Output Height (Pixels)',
		name: 'height',
		type: 'number',
		displayOptions: { show: showFor },
		typeOptions: { minValue: 1 },
		default: 1920,
	},
	{
		displayName: 'Duration (Seconds)',
		name: 'durationSecs',
		type: 'number',
		displayOptions: { show: showFor },
		typeOptions: { minValue: 1, maxValue: 180 },
		default: 30,
		description: 'Optional clip duration in seconds, with free plans usually capped at 10 seconds',
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		displayOptions: { show: showFor },
		default: '',
		placeholder: 'you@example.com',
		description: 'Optional email to associate with the job',
	},
	{
		displayName: 'Advanced Settings',
		name: 'outputOptions',
		type: 'collection',
		placeholder: 'Add Setting',
		displayOptions: { show: showFor },
		default: {},
		options: [
			{
				displayName: 'Custom Save Path',
				name: 'outputKey',
				type: 'string',
				default: '',
				placeholder: 'my-folder/result.mp4',
				description: 'Where to save the result in your storage. Leave empty to auto-generate.',
			},
		],
	},
];
